# storage:
#   enabled: true
#   volumes:
#     - name: "config"
#       type: "pvc"
#       mountPath: "/app/config"
#       accessModes:
#       - ReadWriteOnce
#       storageClass: "local-path"
#       size: 1Gi
#       readOnly: false