{{- define "common-helm-library.resources.certificate" -}}
{{- if and (eq .Release.Name "traefik") .Values.tls.cloudflare }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-production
  namespace: platform-ingress
spec:
  secretName: cloudflare-letsencrypt-production-certificate
  issuerRef:
    kind: ClusterIssuer
    name: cloudflare-letsencrypt-production
  commonName: {{ .Values.tls.cloudflare.commonName | quote }}
  dnsNames:
    - {{ .Values.tls.cloudflare.commonName | quote }}
---
{{- end }}
{{- end }}