{{- define "common-helm-library.resources.deployment" -}}
{{- $requiredMsg := include "common-helm-library.helpers.chart.check-required-value" . -}}
{{- if eq .Values.type "deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ required (printf $requiredMsg "name") .Values.name | quote }}
  labels:
    {{- include "common-helm-library.helpers.metadata.labels" . | nindent 4 }}
spec:
  securityContext:
    fsGroup: {{ .Values.securityContext.runAsUser }}
    fsGroupChangePolicy: {{ .Values.securityContext.fsGroupChangePolicy }}
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  selector:
    matchLabels:
      {{- include "common-helm-library.helpers.metadata.selector-labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common-helm-library.helpers.metadata.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ required (printf $requiredMsg "name") .Values.name | quote }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{ include "common-helm-library.helpers.containers.main" . | nindent 6 }}
      {{ include "common-helm-library.helpers.volumes.main" . | nindent 6 }}
---
{{- end }}
{{- end }}