{{- define "common-helm-library.resources.deployment" -}}
{{- $requiredMsg := include "common-helm-library.helpers.chart.check-required-value" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ required (printf $requiredMsg "name") .Values.name | quote }}
  labels:
    {{- include "common-helm-library.helpers.metadata.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  minReadySeconds: {{ .Values.deployment.minReadySeconds }}
  strategy: {}
  selector:
    matchLabels:
      {{- include "common-helm-library.helpers.metadata.selector-labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common-helm-library.helpers.metadata.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | quote }}
      {{- if .Values.deployment.imagePullSecret }}
      imagePullSecrets:
      - name: {{ required (printf $requiredMsg "deployment.imagePullSecret") .Values.deployment.imagePullSecret| quote }}
      {{- end }}
      securityContext:
        fsGroup: {{ .Values.deployment.runAsUser }}
        runAsUser: {{ .Values.deployment.runAsUser }}
        runAsGroup: 
        runAsNonRoot: {{ .Values.deployment.runAsNonRoot }}
        fsGroupChangePolicy:
        seLinuxOptions:
        seccompProfile:
        supplementalGroups:
        sysctls: 
        appArmorProfile:
      containers:
      {{ include "common-helm-library.helpers.container.main" . | nindent 6 }}
      {{- if .Values.storage.enabled }}
      volumes:
        {{- range .Values.storage.volumes }}
        {{- if eq .type "configMap" }}
        - name: {{ .name }}
          configMap:
            name: {{ .configMapName }}
            items:
              {{- range .items }}
              - key: {{ .key }}
                path: {{ .path }}
              {{- end }}
        {{- else if eq .type "emptyDir" }}
        - name: {{ .name }}
          emptyDir:
            {{- if .ramDisk }}
            medium: "Memory"
            {{- end }}
            {{- if .sizeLimit }}
            sizeLimit: {{ .sizeLimit }}
            {{- end }}
        {{- else if eq .type "downwardAPI" }}
        - name: {{ .name }}
          downwardAPI:
            items:
              {{- range .items }}
              - path: {{ .path }}
                fieldRef:
                  fieldPath: {{ .fieldRef.fieldPath }}
              {{- end }}
        {{- else if eq .type "pvc" }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ $.Release.Name }}-{{ .name }}
        {{- end }}
        {{- end }}
        {{- end }}
---
{{- end }}