{{- define "common-helm-library.resources.persistentvolumeclaim" -}}
{{- $requiredMsg := include "common-helm-library.helpers.chart.check-required-value" . -}}
{{- range .Values.storage }}
{{- if eq .type "pvc" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
spec:
  storageClassName: ""
  accessModes: {{ .accessModes | toYaml | nindent 10 }}
  resources:
    requests:
      storage: {{ .size }}
  volumeName: nfs
---      
{{- end }}
{{- end }}
{{- end }}