{{ define "common-helm-library.resources.persistentVolume" }}
{{ if .Values.storage.enabled }}
{{ range .Values.storage.persistentVolumes }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
spec:
  capacity:
    storage: {{ .sizeLimit }}
  volumeMode: {{ .volumeMode }}
  accessModes: {{ .accessModes | toYaml | nindent 10 }}
  mountOptions: {{ .mountOptions | toYaml | nindent 10 }}
  {{ if .nfs }}
  nfs:
    path: {{ .nfs.path }}
    server: {{ .nfs.server }}
  {{ end }}
---
{{ end }}