{{- define "common-helm-library.resources.role" -}}
{{- $requiredMsg := include "common-helm-library.helpers.chart.check-required-value" . -}}
{{- range .Values.rbac }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .type }}
metadata:
  name: {{ .name }}
rules:
{{ toYaml .rules | indent 2 }}
{{- end }}
{{- end }}
