{{- define "common-helm-library.resources.rolebinding" -}}
{{- $requiredMsg := include "common-helm-library.helpers.chart.check-required-value" . -}}
{{- if and .Values.rbac.enabled .Values.serviceAccount.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.rbac.type }}Binding
metadata:
  name: {{ .Release.Name }}
roleRef:
  kind: {{ .Values.rbac.type }}
  name: {{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
{{- end }}
---
{{- end }}