{{- define "common-helm-library.resources.rolebinding" -}}
{{- $requiredMsg := include "common-helm-library.helpers.chart.check-required-value" . -}}
{{- if .Values.serviceAccount }}
{{- range .Values.rbac }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .type }}Binding
metadata:
  name: {{ .name }}
roleRef:
  kind: {{ .type }}
  name: {{ .name }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ required (printf $requiredMsg "name") $.Values.name | quote }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}