{{- define "common-helm-library.resources.service" -}}
{{- $requiredMsg := include "common-helm-library.helpers.chart.check-required-value" . -}}
{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ required (printf $requiredMsg "name") $.Values.name | quote}}
spec:
  type: {{ required (printf $requiredMsg ".type") .type | quote }}
  selector:
    app.kubernetes.io/name: {{ $.Relase.Name }}
  {{- if .loadBalancerIP }}
  loadBalancerIP: {{ .loadBalancerIP }}
  {{- end }}
  {{- if .publishNotReadyAddresses }}
  publishNotReadyAddresses: {{ .publishNotReadyAddresses }}
  {{- end }}
  {{- if .headless }}
  clusterIP: None
  {{- end }}
  ports:
  {{- range .ports }}
  - name: {{ .name }}
    protocol: {{ .protocol }}
    port: {{ .port }}
  {{- end }}
---  
{{- end -}}
{{- end -}}