{{- define "common-helm-library.resources.serviceaccount" -}}
{{- $requiredMsg := include "common-helm-library.helpers.chart.check-required-value" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required (printf $requiredMsg "name") .Values.name | quote }}
  labels:
    {{- include "common-helm-library.helpers.metadata.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
---
{{- end }}