{{- define "common-helm-library.resources.service" -}}
{{- $requiredMsg := include "common-helm-library.helpers.chart.check-required-value" . -}}
{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ required (printf $requiredMsg "name") $.Values.name | quote}}
  labels:
    {{- include "common-helm-library.helpers.metadata.labels" $ | nindent 4 }}
spec:
  type: {{ required (printf $requiredMsg ".type") .type | quote }}
  selector:
    {{- include "common-helm-library.helpers.metadata.selector-labels" $ | nindent 6 }}
  {{- if .loadBalancerIP }}
  loadBalancerIP: {{ .loadBalancerIP }}
  {{- end }}
  {{- if .publishNotReadyAddresses }}
  publishNotReadyAddresses: {{ .publishNotReadyAddresses }}
  {{- end }}
  {{- if .headless }}
  clusterIP: None
  {{- end }}
  ports:
  {{- range .ports }}
  - name: {{ .name }}
    protocol: {{ .protocol }}
    port: {{ .port }}
  {{- end }}
---
{{- end -}}
{{- end -}}