{{- define "common-helm-library.resources.storageClass" -}}
{{- $requiredMsg := include "common-helm-library.helpers.chart.check-required-value" . -}}
{{- if .Values.storageClass -}}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ required (printf $requiredMsg "name") .Values.name | quote }}
  labels:
    {{- include "common-helm-library.helpers.metadata.labels" . | nindent 4 }}
  {{- if .Values.storageClass.defaultClass }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: {{ required (printf $requiredMsg "name") .Values.name | quote }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
{{- if .Values.storageClass.allowVolumeExpansion }}
allowVolumeExpansion: {{ .Values.storageClass.allowVolumeExpansion }}
{{- end }}
volumeBindingMode: Immediate
{{- with .Values.storageClass.parameters }}
parameters:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.storageClass.mountOptions }}
mountOptions:
  {{- toYaml . | nindent 2 }}
{{- end }}
---
{{- end }}
{{- end }}