{{ define "common-helm-library.resources.storageClass" -}}
{{ if .Values.storageClass.enabled -}}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{ include "common-helm-library.helpers.metadata.labels" . | nindent 4 }}
    {{ if .Values.storageClass.labels }}
    {{ toYaml .Values.storageClass.labels | nindent 4 }}
    {{ end }}
  annotations:
    {{ include "common-helm-library.helpers.metadata.annotations" $ | nindent 4 }}
    {{ if .Values.storageClass.annotations }}
    {{ toYaml .Values.storageClass.annotations | nindent 4 }}
    {{ end }}
  {{ if .Values.storageClass.defaultClass }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{ end }}
{{ if .Values.storageClass.provisioner }}
provisioner: {{ .Values.storageClass.provisioner }}
{{ end }}
{{ if .Values.storageClass.reclaimPolicy }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
{{ end }}
{{ if .Values.storageClass.allowVolumeExpansion }}
allowVolumeExpansion: {{ .Values.storageClass.allowVolumeExpansion }}
{{ end }}
{{ if .Values.storageClass.volumeBindingMode }}
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode }}
{{ end }}
{{ with .Values.storageClass.parameters }}
parameters:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.storageClass.mountOptions }}
mountOptions:
  {{- toYaml . | nindent 2 }}
{{- end }}
---
{{- end }}
{{- end }}