{{- define "common-helm-library.resources.workload" -}}
{{- $requiredMsg := include "common-helm-library.helpers.chart.check-required-value" . -}}
apiVersion: apps/v1
kind: {{ .Values.type | indent 1 }}
metadata:
  name: {{ required (printf $requiredMsg "name") .Values.name | quote }}
  labels:
    {{- include "common-helm-library.helpers.metadata.labels" . | nindent 4 }}
spec:
  {{- if ne .Values.type "Daemonset" }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- if eq .Values.type "StatefulSet" }}
  podManagementPolicy: OrderedReady
  {{- end }}
  {{- if and (eq .Values.type "StatefulSet") .Values.Service }}
  serviceName: {{ required (printf $requiredMsg "name") .Values.name | quote }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common-helm-library.helpers.metadata.selector-labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common-helm-library.helpers.metadata.labels" . | nindent 8 }}
    spec:
      {{- include "common-helm-library.helpers.containers.main" . | nindent 6 }}
      {{- include "common-helm-library.helpers.initcontainers.main" . | nindent 6 }}
      {{- include "common-helm-library.helpers.serviceaccount.main" . | nindent 6 }}
      {{- include "common-helm-library.helpers.priorityclass.main" . | nindent 6 }}
      {{- include "common-helm-library.helpers.volumes.main" . | nindent 6 }}
---
{{- end }}